version: "3.8"

services:
  sqlite-web:
    image: coleifer/sqlite-web
    container_name: sqlite-web
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    environment:
      - DATABASE=/data/database.db
