server:
  port: ${SERVER_PORT:8080}
  max-http-request-header-size: 65536  # Tamanho máximo do cabeçalho HTTP
  tomcat:
    max-swallow-size: 2MB             # Limita o tamanho do corpo da requisição
    connection-timeout: 30000         # Tempo de espera para novas conexões (30 segundos)
    max-connections: 50               # Número máximo de conexões simultâneas
    max-threads: 10                   # Limita o número de threads que o Tomcat pode usar (ajustado para baixo consumo)

spring:
  application:
    name: mxmcimentos

  # Configuração do DataSource com HikariCP (pool de conexões)
  datasource:
    url: jdbc:sqlite:/home/mxm-database.db?date_class=TEXT
    driver-class-name: org.sqlite.JDBC
    username: ""
    password: ""


  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true  # Adia a execução dos scripts SQL até após o Hibernate criar o esquema
  web:
    locale: pt_BR
    locale-resolver: fixed
    resources:
      static-locations: classpath:/static/

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false  # Desativa o cache do Thymeleaf para reduzir o consumo de memória

  # Desativa o monitoramento de sessões (menos uso de memória)
  session:
    timeout: 15m   # Tempo de expiração da sessão, reduzindo a carga de sessões persistentes

  # Monitoramento e logging
  logging:
    level:
      org.springframework: ERROR  # Aumenta o nível para evitar logs detalhados
      org.hibernate: ERROR         # Reduz ainda mais o log do Hibernate
      org.apache: ERROR            # Caso utilize Apache ou outras dependências

  sql:
    init:
      mode: always
